extensions:
    reference-data-job-instance-csv-export-edit:
        module: pim/form/common/edit-form

    reference-data-job-instance-csv-export-edit-main-image:
        module: pim/form/common/main-image
        parent: reference-data-job-instance-csv-export-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportCSV.svg

    reference-data-job-instance-csv-export-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: reference-data-job-instance-csv-export-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    reference-data-job-instance-csv-export-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: reference-data-job-instance-csv-export-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    reference-data-job-instance-csv-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: reference-data-job-instance-csv-export-edit
        position: 1000

    reference-data-job-instance-csv-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: reference-data-job-instance-csv-export-edit
        targetZone: content
        position: 100

    reference-data-job-instance-csv-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: reference-data-job-instance-csv-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_common.properties
            tabCode: reference-data-job-instance-properties

    reference-data-job-instance-csv-export-edit-global:
        module: pim/job/common/edit/properties
        parent: reference-data-job-instance-csv-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode: reference-data-job-instance-global

    reference-data-job-instance-csv-export-edit-history:
        module: pim/common/tab/history
        parent: reference-data-job-instance-csv-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_history
        targetZone: container
        position: 120
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_common.history
            tabCode: reference-data-job-instance-history

    reference-data-job-instance-csv-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: reference-data-job-instance-csv-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_common.code
            readOnly: true

    reference-data-job-instance-csv-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: reference-data-job-instance-csv-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_common.label
            readOnly: false

    reference-data-job-instance-csv-export-edit-properties-reference-data-names:
        module: custom_entity/field/select2
        parent: reference-data-job-instance-csv-export-edit-global
        position: 100
        targetZone: properties
        config:
            fieldCode: configuration.reference_data_name
            readOnly: false
            label: pim_custom_entity.export.csv.entity_name.label
            tooltip: pim_custom_entity.export.csv.entity_name.help

    reference-data-job-instance-csv-export-edit-properties-file-path:
        module: pimimportexport/js/job/common/edit/storage-form
        parent: reference-data-job-instance-csv-export-edit-global
        position: 105
        targetZone: additional-properties
        config:
            tabCode: pim-job-instance-properties
            jobType: export
            fileExtension: csv

    reference-data-job-instance-csv-export-edit-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: reference-data-job-instance-csv-export-edit-global
        position: 110
        targetZone: properties
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_import_export.form.job_instance.tab.properties.decimal_separator.help

    reference-data-job-instance-csv-export-edit-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: reference-data-job-instance-csv-export-edit-global
        position: 120
        targetZone: properties
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.date_format.title
            tooltip: pim_import_export.form.job_instance.tab.properties.date_format.help

    reference-data-job-instance-csv-export-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: reference-data-job-instance-csv-export-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_import_export.form.job_instance.tab.properties.delimiter.help

    reference-data-job-instance-csv-export-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: reference-data-job-instance-csv-export-edit-global
        position: 140
        targetZone: properties
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_import_export.form.job_instance.tab.properties.enclosure.help

    reference-data-job-instance-csv-export-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: reference-data-job-instance-csv-export-edit-global
        position: 150
        targetZone: properties
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.with_header.title
            tooltip: pim_import_export.form.job_instance.tab.properties.with_header.help

    reference-data-job-instance-csv-export-edit-label:
        module: pim/job/common/edit/label
        parent: reference-data-job-instance-csv-export-edit
        targetZone: title
        position: 100

    reference-data-job-instance-csv-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: reference-data-job-instance-csv-export-edit
        targetZone: meta
        position: 100

    reference-data-job-instance-csv-export-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: reference-data-job-instance-csv-export-edit
        targetZone: buttons
        position: 50

    reference-data-job-instance-csv-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: reference-data-job-instance-csv-export-edit-secondary-actions
        targetZone: secondary-actions
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    reference-data-job-instance-csv-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: reference-data-job-instance-csv-export-edit
        targetZone: buttons
        position: 120

    reference-data-job-instance-csv-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: reference-data-job-instance-csv-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    reference-data-job-instance-csv-export-edit-state:
        module: pim/form/common/state
        parent: reference-data-job-instance-csv-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    reference-data-job-instance-csv-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: reference-data-job-instance-csv-export-edit
